<a href="https://colab.research.google.com/github/KyriakosPsa/ML_CB_Project/blob/master/Methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [54]:
from sklearn.decomposition import PCA

In [59]:
cell_counts = pd.read_csv("/content/drive/MyDrive/Datasets/counts.csv")
pooled_samples = pd.read_csv("/content/drive/MyDrive/Datasets/pooled.csv")
gene_info = pd.read_csv("/content/drive/MyDrive/Datasets/genes.csv")

In [60]:
cell_counts

,Unnamed: 0,TSPAN6,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,NFYA,...,RP11-548H3.1,LL09NC01-139C3.1,RP11-196O16.1,RP11-465N4.5,RP11-731C17.2,RP11-114I8.4,RP11-180C16.1,AP000230.1,EC2,EC15
0,BC01_02,0.000000,5.692929,2.097611,0.000000,0.0,0.0,3.411426,1.952334,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,2.801159,0.0,14.168620,9.071757
1,BC01_03,0.000000,6.924337,0.000000,3.849999,0.0,0.0,5.223423,2.589763,1.056584,...,1.803227,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,14.258893,9.353742
2,BC01_04,0.000000,2.994580,6.542722,0.000000,0.0,0.0,0.000000,6.769640,0.000000,...,0.000000,0.0,4.631104,0.0,0.0,0.0,0.000000,0.0,14.799936,9.841439
3,BC01_05,0.000000,7.506605,2.895303,0.000000,0.0,0.0,0.000000,1.731183,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,4.296457,0.0,14.929793,9.910448
4,BC01_06,0.000000,5.048323,5.925525,0.000000,0.0,0.0,3.235727,5.743892,0.000000,...,0.000000,0.0,3.957915,0.0,0.0,0.0,0.000000,0.0,15.571204,11.003855
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
510,BC11_69,0.000000,0.000000,0.000000,0.000000,0.0,0.0,3.010780,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,15.844541,11.159815
511,BC11_70,0.000000,0.000000,0.000000,7.958205,0.0,0.0,2.456806,0.000000,5.760487,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,15.993631,11.462753
512,BC11_78,0.000000,7.098769,0.000000,4.560715,0.0,0.0,0.000000,6.155021,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,4.606442,0.0,15.030413,10.691037
513,BC11_81,7.656925,4.525443,0.000000,3.626439,0.0,0.0,2.411426,1.084064,2.837943,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,16.732676,11.748415
514,BC11_88,0.000000,7.683556,3.395063,0.000000,0.0,0.0,0.000000,4.212569,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,15.811099,10.844243